# Generated by Django 4.0.3 on 2022-05-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
