# Generated by Django 4.0.3 on 2022-06-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_prd_addedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='prd_addedBy',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
