# Generated by Django 4.0.3 on 2022-06-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='product',
        ),
    ]
