# Generated by Django 4.0.3 on 2022-06-12 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_orderitem_order_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='prd_addedBy',
        ),
    ]
