# Generated by Django 4.0.3 on 2022-06-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_orderitem_prd_addedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ord_prd_addedBy',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
