# Generated by Django 4.0.3 on 2022-06-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_orderitem_ord_prd_addedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
