# Generated by Django 4.0.3 on 2022-05-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artisans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artisan_name', models.CharField(max_length=200, null=True)),
                ('artisan_email', models.CharField(max_length=200)),
                ('artisan_password', models.CharField(max_length=200, null=True)),
                ('artisan_phno', models.IntegerField(max_length=200, null=True)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('zip_code', models.IntegerField(max_length=200, null=True)),
                ('company_address', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
