# Generated by Django 4.0.3 on 2022-05-31 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtisanDashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisans',
            name='artisan_password',
        ),
    ]
